apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guest-demo
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guest-demo
  targetCPUUtilizationPercentage: 50
