kind: Service
apiVersion: v1
metadata:
  name: guest-demo
  labels:
    app: guest-demo
spec:
  selector:
    app: guest-demo
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    nodePort: {{ServerNodePort}}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: guest-demo
  labels:
    app: guest-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guest-demo
  template:
    metadata:
      labels:
        app: guest-demo
    spec:
      containers:
      - name: server
        image: {{ImageRepoHost}}:{{RegistryNodePort}}/guest-demo
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 0.1
